# Generated by Django 3.2.4 on 2022-07-26 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unsaTur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zontur',
            name='identificador_usuario',
            field=models.ForeignKey(db_column='identificador_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, to='unsaTur.usucab'),
            preserve_default=False,
        ),
    ]
